language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
# - 3.8-dev # buggy in travis
- 3.7
- 3.6
- 3.5

matrix:
  include:
  - os: linux
    name: Install Test
    python: 3.7
    install:
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests
  - os: linux
    name: PEP8 MyPy Covs
    python: 3.7
    install: pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .
    - pytest -r a -v
    after_success:
    - pytest --cov
    - coveralls

install: pip install -e .[tests]

script: pytest -r a -v

